# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nikte < Formula
  desc "Fast CLI for ephemeral content management"
  homepage "https://github.com/sim4gh/nikte-cli"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.9.0/nikte-cli_0.9.0_darwin_amd64.tar.gz"
      sha256 "063c9ad537c4f5503873b7b2c5e35f43dca0a22c765296b36617175984ab3b17"

      define_method(:install) do
        bin.install "nk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.9.0/nikte-cli_0.9.0_darwin_arm64.tar.gz"
      sha256 "e1df6f7200a31cc77e7ae45400e48747db909aa9b57674b5e5ea1f09c8019e3e"

      define_method(:install) do
        bin.install "nk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.9.0/nikte-cli_0.9.0_linux_amd64.tar.gz"
      sha256 "d57502569fe5c41bde13fc668bd7d83f4220beaec93dd5eb5ac7d558f795381b"
      define_method(:install) do
        bin.install "nk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.9.0/nikte-cli_0.9.0_linux_arm64.tar.gz"
      sha256 "6a4ff32e69e7b13e42257dc22d08e8e9eddc54b9d1f76fb29f869c36acfae454"
      define_method(:install) do
        bin.install "nk"
      end
    end
  end

  test do
    system "#{bin}/nk", "--version"
  end
end
