# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nikte < Formula
  desc "Fast CLI for ephemeral content management"
  homepage "https://github.com/sim4gh/nikte-cli"
  version "0.8.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.8.2/nikte-cli_0.8.2_darwin_amd64.tar.gz"
      sha256 "22901f2e953f21c17d163722640ab485a515754fcb2e14da701718ba331dee58"

      define_method(:install) do
        bin.install "nk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.8.2/nikte-cli_0.8.2_darwin_arm64.tar.gz"
      sha256 "71937df33adc610e74e57764f301cd5e5861a3f09f3b30fa8e338a1cbdce7bcf"

      define_method(:install) do
        bin.install "nk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.8.2/nikte-cli_0.8.2_linux_amd64.tar.gz"
      sha256 "b6c7333ab1f872fce1508294163bbaabbf0ecdaa211fd457ebf68cab18524971"
      define_method(:install) do
        bin.install "nk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.8.2/nikte-cli_0.8.2_linux_arm64.tar.gz"
      sha256 "b1b80d86eeb78ecad018f3f1a6129284b4346a01993bfc626ba11d96c78be405"
      define_method(:install) do
        bin.install "nk"
      end
    end
  end

  test do
    system "#{bin}/nk", "--version"
  end
end
