# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oio < Formula
  desc "Fast CLI for ephemeral content management"
  homepage "https://github.com/sim4gh/oio-go"
  version "2.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sim4gh/oio-go/releases/download/v2.4.2/oio-go_2.4.2_darwin_amd64.tar.gz"
      sha256 "a46cef1560d61219a8b4fdf81d8d256bd32498285a696faba06168f12f6ffe0a"

      define_method(:install) do
        bin.install "oio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sim4gh/oio-go/releases/download/v2.4.2/oio-go_2.4.2_darwin_arm64.tar.gz"
      sha256 "15a7201647a6a7e427867c90c990bd4c05832e0623d285ce565a237f37e1e14b"

      define_method(:install) do
        bin.install "oio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sim4gh/oio-go/releases/download/v2.4.2/oio-go_2.4.2_linux_amd64.tar.gz"
      sha256 "926097e5a895920d342108d36d0f130c1c897926f5d660a5b9f8b6f153be8752"
      define_method(:install) do
        bin.install "oio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sim4gh/oio-go/releases/download/v2.4.2/oio-go_2.4.2_linux_arm64.tar.gz"
      sha256 "d91399cf0164e9d120cc3622cc50db748197751a06609b145ecef7deb805e3e5"
      define_method(:install) do
        bin.install "oio"
      end
    end
  end

  test do
    system "#{bin}/oio", "--version"
  end
end
